### ISSUE TITLE
Jsonnet.org demo broken

### ISSUE THREAD

**Issue by peterthenelson** [google/jsonnet#248]
(On linux chrome)
http://jsonnet.org/docs/demo.html

libjsonnet.js:7498 Uncaught RangeError: Maximum call stack size exceeded(…)
invoke_iiiiii @ libjsonnet.js:7498
_jsonnet_evaluate_snippet @ libjsonnet.js:119759
(anonymous function) @ VM559:11
jsonnet_evaluate_snippet_wrapped @ demo.html:636
compute @ demo.html:647
replace @ demo.html:652
(anonymous function) @ demo.html:654

**Comment by peterthenelson** [comment]
Oh, and expanding the "..." in the error message:
    at Array.__ZN12_GLOBAL__N_16Parser5parseEi (http://jsonnet.org/js/libjsonnet.js:29329:43)
    at Object.dynCall_iii (http://jsonnet.org/js/libjsonnet.js:144412:39)
    at invoke_iii (http://jsonnet.org/js/libjsonnet.js:7487:33)
    at Array.__ZN12_GLOBAL__N_16Parser5parseEi (http://jsonnet.org/js/libjsonnet.js:32106:11)
    at Object.dynCall_iii (http://jsonnet.org/js/libjsonnet.js:144412:39)
    at invoke_iii (http://jsonnet.org/js/libjsonnet.js:7487:33)
    at Array.__ZN12_GLOBAL__N_16Parser5parseEi (http://jsonnet.org/js/libjsonnet.js:32106:11)
    at Object.dynCall_iii (http://jsonnet.org/js/libjsonnet.js:144412:39)
    at invoke_iii (http://jsonnet.org/js/libjsonnet.js:7487:33)
    at Array.__ZN12_GLOBAL__N_16Parser5parseEi (http://jsonnet.org/js/libjsonnet.js:32106:11)

**Comment by sparkprime** [comment]
The code hasn't changed for 7 months so I guess it is chrome that has reduced the stack size or made some other change.  Thanks for the report.

**Comment by sparkprime** [comment]
Looks like this is a known problem in chrome, so I'm going to close.

https://groups.google.com/a/chromium.org/forum/#!topic/chromium-discuss/YxMaEsEqp3k

(It works in Firefox, and apparently in more recent chrome although I haven't tested that).
