### ISSUE TITLE
ASAN: 386-byte memory leak

### ISSUE THREAD

**Issue by geeknik** [google/jsonnet#295]
Compiled with afl-clang-fast. 

`./jsonnet -h`
```
./jsonnet -h
Jsonnet commandline interpreter v0.9.1
Typical Usage:
jsonnet [<cmd>] {<option>} <filename>
Where <cmd> is one of {eval, fmt} and defaults to eval.

**SNIP**

Note that since filenames and jsonnet programs can begin with -, it is advised to
use -- if the argument is unknown, e.g. jsonnet -- "$FILENAME".

=================================================================
==21660==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 240 byte(s) in 1 object(s) allocated from:
    #0 0x4834bb in operator new(unsigned long) (/root/jsonnet/jsonnet+0x4834bb)
    #1 0x660a1f in jsonnet_make /root/jsonnet/core/libjsonnet.cpp:281:5
    #2 0x7fc1e7a1db44 in __libc_start_main /build/glibc-qK83Be/glibc-2.19/csu/libc-start.c:287

Indirect leak of 130 byte(s) in 2 object(s) allocated from:
    #0 0x4834bb in operator new(unsigned long) (/root/jsonnet/jsonnet+0x4834bb)
    #1 0x7fc1e807be98 in std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xbee98)

Indirect leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x4834bb in operator new(unsigned long) (/root/jsonnet/jsonnet+0x4834bb)
    #1 0x52e7a5 in __gnu_cxx::new_allocator<std::string>::allocate(unsigned long, void const*) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/ext/new_allocator.h:104:27
    #2 0x52e7a5 in std::allocator_traits<std::allocator<std::string> >::allocate(std::allocator<std::string>&, unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/alloc_traits.h:357
    #3 0x52e7a5 in std::_Vector_base<std::string, std::allocator<std::string> >::_M_allocate(unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/stl_vector.h:170
    #4 0x52e7a5 in void std::vector<std::string, std::allocator<std::string> >::_M_emplace_back_aux<std::string>(std::string&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/vector.tcc:412
    #5 0x67fde5 in void std::vector<std::string, std::allocator<std::string> >::emplace_back<std::string>(std::string&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/vector.tcc:101:4
    #6 0x67fde5 in JsonnetVm::JsonnetVm() /root/jsonnet/core/libjsonnet.cpp:178
    #7 0x660a51 in jsonnet_make /root/jsonnet/core/libjsonnet.cpp:281:5
    #8 0x7fc1e7a1db44 in __libc_start_main /build/glibc-qK83Be/glibc-2.19/csu/libc-start.c:287

SUMMARY: AddressSanitizer: 386 byte(s) leaked in 4 allocation(s).
```

**Comment by sparkprime** [comment]
True, not all the early returns in main() call jsonnet_destroy(vm) as they should do.
