### ISSUE TITLE
Failed to build libjsonnet.js using emscripten

### ISSUE THREAD

**Issue by sbarzowski** [google/jsonnet#358]
I tried building js version, but emscripten failed in a way that is completely mysterious to me. I don't really need js version for anything now, but, though.
```
sbarzowski@sbarzowski01:~/Work/jsonnet$ make libjsonnet.js 
em++ -s 'EXPORTED_FUNCTIONS=["_jsonnet_make", "_jsonnet_evaluate_snippet", "_jsonnet_realloc", "_jsonnet_destroy"]' -g -O3 -Wall -Wextra -Woverloaded-virtual -pedantic -std=c++0x -fPIC -Iinclude -Ithird_party/md5 -Os --memory-init-file 0 -s DISABLE_EXCEPTION_CATCHING=0 -s OUTLINING_LIMIT=10000  core/desugarer.cpp core/formatter.cpp core/lexer.cpp core/libjsonnet.cpp core/parser.cpp core/pass.cpp core/static_analysis.cpp core/string_utils.cpp core/vm.cpp third_party/md5/md5.cpp -o libjsonnet.js
aborting from js compiler due to exception: unknown vector type <4 x i8> | undefined
aborting from js compiler due to exception: unknown vector type <4 x i8> | undefined
aborting from js compiler due to exception: unknown vector type <4 x i8> | undefined
aborting from js compiler due to exception: unknown vector type <4 x i8> | undefined
aborting from js compiler due to exception: unknown vector type <4 x i8> | undefined
Traceback (most recent call last):
  File "/usr/share/emscripten/emscripten.py", line 1352, in <module>
    _main(environ=os.environ)
  File "/usr/share/emscripten/emscripten.py", line 1340, in _main
    temp_files.run_and_clean(lambda: main(
  File "/usr/share/emscripten/tools/tempfiles.py", line 39, in run_and_clean
    return func()
  File "/usr/share/emscripten/emscripten.py", line 1348, in <lambda>
    DEBUG_CACHE=DEBUG_CACHE,
  File "/usr/share/emscripten/emscripten.py", line 1235, in main
    jcache=jcache, temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
  File "/usr/share/emscripten/emscripten.py", line 292, in emscript
    assert len(output) == 2, 'Did not receive forwarded data in an output - process failed? We only got: ' + output[0][-3000:]
AssertionError: Did not receive forwarded data in an output - process failed? We only got: 0) {
    $_01=-1;

    return (($_01)|0);
   }
   $22=(($this+20)|0);
   $23=((HEAP32[(($22)>>2)])|0);
   $24=$12;
   $25=$23;
   $26=((($24)-($25))|0);
   $27=(($this+44)|0);
   $28=((HEAP32[(($27)>>2)])|0);
   $29=$28;
   $30=((($29)-($25))|0);
   $31=(($this+32)|0);
   __THREW__ = 0;invoke_vii('{{ FI___ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE9push_backEc }}',(($31)|0),((0)|0));
   do {
    if (!__THREW__) {
     $33=$31;
     $34=$31;
     $35=((HEAP8[($34)])|0);
     $36=$35&1;
     $37=(($36<<24)>>24)==0;
     if ($37) {
      $42=10;
     } else {
      $39=(($31)|0);
      $40=((HEAP32[(($39)>>2)])|0);
      $41=$40&-2;
      $phitmp=((($41)-(1))|0);
      $42=$phitmp;
     }

     __THREW__ = 0;invoke_viii('{{ FI___ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6resizeEjc }}',(($31)|0),(($42)|0),((0)|0));
     if (!(!__THREW__)) {
      __THREW__ = 0;
      break;
     }
     $43=((HEAP8[($34)])|0);
     $44=$43&1;
     $45=(($44<<24)>>24)==0;
     if ($45) {
      $50=(($33+1)|0);
      $51=$50;
     } else {
      $47=(($this+40)|0);
      $48=((HEAP32[(($47)>>2)])|0);
      $51=$48;
     }

     $52=($43&255);
     $53=$52&1;
     $54=($53|0)==0;
     if ($54) {
      $59=$52>>>1;
      $60=$59;
     } else {
      $56=(($this+36)|0);
      $57=((HEAP32[(($56)>>2)])|0);
      $60=$57;
     }

     $61=(($51+$60)|0);
     HEAP32[(($22)>>2)]=$51;
     HEAP32[(($13)>>2)]=$61;
     $62=(($51+$26)|0);
     HEAP32[(($11)>>2)]=$62;
     $63=(($51+$30)|0);
     HEAP32[(($27)>>2)]=$63;
     $70=$62;$69=$63;$68=$61;$_pre_phi=$17;
     break L4;
    } else {
     __THREW__ = 0;
    }
   } while(0);
   $65$0 = ((___cxa_find_matching_catch(-1, -1,((0)|0)))|0); $65$1 = tempRet0;
   $66=$65$0;
   $67=((___cxa_begin_catch((($66)|0)))|0);
   ___cxa_end_catch();
   $_01=-1;

   return (($_01)|0);
  } else {
   $_phi_trans_insert=(($this+44)|0);
   $_pre=((HEAP32[(($_phi_trans_insert)>>2)])|0);
   $_pre2=(($this+48)|0);
   $70=$12;$69=$_pre;$68=$14;$_pre_phi=$_pre2;
  }
 } while(0);




 $71=(($70+1)|0);
 $72=(($this+44)|0);
 $73=($71>>>0)<($69>>>0);
 $74=($73?$69:$71);
 HEAP32[(($72)>>2)]=$74;
 $75=((HEAP32[(($_pre_phi)>>2)])|0);
 $76=$75&8;
 $77=($76|0)==0;
 if (!($77)) {
  $79=(($this+32)|0);
  $80=$79;
  $81=((HEAP8[($80)])|0);
  $82=$81&1;
  $83=(($82<<24)>>24)==0;
  if ($83) {
   $88=$79;
   $89=(($88+1)|0);
   $90=$89;
  } else {
   $85=(($this+40)|0);
   $86=((HEAP32[(($85)>>2)])|0);
   $90=$86;
  }

  $91=(($90+$10)|0);
  HEAP32[(($6)>>2)]=$90;
  HEAP32[(($4)>>2)]=$91;
  $92=(($this+16)|0);
  HEAP32[(($92)>>2)]=$74;
 }
 $94=($70|0)==($68|0);
 if ($94) {
  $96=$this;
  $97=((HEAP32[(($96)>>2)])|0);
  $98=(($97+52)|0);
  $99=((HEAP32[(($98)>>2)])|0);
  $100=$__c&255;
  $101=((FUNCTION_TABLE_iii[($99)&{{{ FTM_iii }}}]($3,$100))|0);
  $_01=$101;

  return (($_01)|0);
 } else {
  $103=(($__c)&255);
  HEAP32[(($11)>>2)]=$71;
  HEAP8[($70)]=$103;
  $104=$__c&255;
  $_01=$104;

  return (($_01)|0);
 }
  return 0;
}


Traceback (most recent call last):
  File "/usr/share/emscripten/emcc", line 1864, in <module>
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/usr/share/emscripten/tools/shared.py", line 1276, in emscripten
    assert os.path.exists(filename + '.o.js') and len(open(filename + '.o.js', 'r').read()) > 0, 'Emscripten failed to generate .js: ' + str(compiler_output)
AssertionError: Emscripten failed to generate .js: 
make: *** [libjsonnet.js] Error 1

sbarzowski@sbarzowski01:~/Work/jsonnet$ em++ --version
emcc (Emscripten GCC-like replacement) 1.10.0 ()
Copyright (C) 2013 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by sbarzowski** [comment]
It looks a lot like: https://github.com/kripken/sql.js/issues/44
which basically boils down to outdated emscripten.

**Comment by sparkprime** [comment]
I used the latest release the other day and it was fine.
