### ISSUE TITLE
Issue building 0.12.0 (0.11.0 works fine) on OSX and Ubuntu

### ISSUE THREAD

**Issue by jsjeannotte** [google/jsonnet#586]
Hi! I can no longer install JSONNET using `pip install jsonnet` because of a compilation error. 
For now, I'm going to pin to 0.11.0, but wanted to let you know of the issue. I can reproduce on OSX and Ubuntu.

```
...
15:19:32     make: 'core/string_utils.o' is up to date.
15:19:32     g++ -c -g -O3 -Wall -Wextra -Woverloaded-virtual -pedantic -std=c++0x -fPIC -Iinclude -Ithird_party/md5 -Ithird_party/json core/vm.cpp -o core/vm.o
15:19:32     core/vm.cpp:26:20: fatal error: json.hpp: No such file or directory
15:19:32     compilation terminated.
15:19:32     Makefile:118: recipe for target 'core/vm.o' failed
15:19:32     make: *** [core/vm.o] Error 1
15:19:32     Traceback (most recent call last):
15:19:32       File "<string>", line 1, in <module>
15:19:32       File "/tmp/pip-install-5qkprtbq/jsonnet/setup.py", line 75, in <module>
15:19:32         test_suite="python._jsonnet_test",
15:19:32       File "/mnt/builds/slave/workspace/PYPI-CLDMTA-copysnake/.tox/py36/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
15:19:32         return distutils.core.setup(**attrs)
15:19:32       File "/apps/python3.6/lib/python3.6/distutils/core.py", line 148, in setup
15:19:32         dist.run_commands()
15:19:32       File "/apps/python3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
15:19:32         self.run_command(cmd)
15:19:32       File "/apps/python3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
15:19:32         cmd_obj.run()
15:19:32       File "/mnt/builds/slave/workspace/PYPI-CLDMTA-copysnake/.tox/py36/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
15:19:32         return orig.install.run(self)
15:19:32       File "/apps/python3.6/lib/python3.6/distutils/command/install.py", line 545, in run
15:19:32         self.run_command('build')
15:19:32       File "/apps/python3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
15:19:32         self.distribution.run_command(command)
15:19:32       File "/apps/python3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
15:19:32         cmd_obj.run()
15:19:32       File "/apps/python3.6/lib/python3.6/distutils/command/build.py", line 135, in run
15:19:32         self.run_command(cmd_name)
15:19:32       File "/apps/python3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
15:19:32         self.distribution.run_command(command)
15:19:32       File "/apps/python3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
15:19:32         cmd_obj.run()
15:19:32       File "/tmp/pip-install-5qkprtbq/jsonnet/setup.py", line 54, in run
15:19:32         raise Exception('Could not build %s' % (', '.join(LIB_OBJECTS)))
15:19:32     Exception: Could not build core/desugarer.o, core/formatter.o, core/libjsonnet.o, core/lexer.o, core/parser.o, core/pass.o, core/static_analysis.o, core/string_utils.o, core/vm.o, third_party/md5/md5.o
```

**Comment by sparkprime** [comment]
Heh I even successfully tested it with a release candidate!  But looks like
even the release candidate is actually broken too. No idea what happened
there.

I just pushed a 0.12.1 to pypi only which should work now.

**Comment by jsjeannotte** [comment]
All good now, thanks @sparkprime !

**Comment by dnk8n** [comment]
This same error when trying to install on containerized Amazon-Linux (jsonnet-0.17.0).

E.g. Dockerfile:

```
FROM public.ecr.aws/lambda/python:3.8

RUN yum install -y make

RUN pip3 install jsonnet
```

**Comment by dnk8n** [comment]
After many iterations and attempts at different things, I have converged on a solution that works for me (you could probably just include `yum install clang` but I don't have the time to test that.

```
FROM public.ecr.aws/lambda/python:3.9

RUN yum install -y clang make
RUN python3 -m pip install --upgrade pip
RUN pip3 install wheel

RUN pip3 install jsonnet
```
