### ISSUE TITLE
Segfault at core/state.h:366

### ISSUE THREAD

**Issue by slene** [google/jsonnet#608]
build from commit google/jsonnet@8d4bf07a

```
# ./jsonnet -J jsonnet --ext-str-file config=test.json test.jsonnet
Segmentation fault
```
gdb

```
(gdb) run
Starting program: ./jsonnet --ext-str-file config=./test.json ./test.jsonnet

Program received signal SIGSEGV, Segmentation fault.
(anonymous namespace)::Heap::markFrom (from=<optimized out>, this=<optimized out>) at core/state.h:366
366	            if (curr->mark != thisMark) {
(gdb) print stack
$1 = {<std::_Vector_base<(anonymous namespace)::Heap::markFrom((anonymous namespace)::HeapEntity*)::State, std::allocator<(anonymous namespace)::Heap::markFrom((anonymous namespace)::HeapEntity*)::State> >> = {
    _M_impl = {<std::allocator<(anonymous namespace)::Heap::markFrom((anonymous namespace)::HeapEntity*)::State>> = {<__gnu_cxx::new_allocator<(anonymous namespace)::Heap::markFrom((anonymous namespace)::HeapEntity*)::State>> = {<No data fields>}, <No data fields>}, _M_start = 0x555555f10ec0, _M_finish = 0x555555f10fc0, _M_end_of_storage = 0x555555f10fc0}}, <No data fields>}
(gdb) print curr
$2 = ((anonymous namespace)::HeapEntity *) 0x0
(gdb) print curr_index
$3 = 7
(gdb) backtrace
#0  (anonymous namespace)::Heap::markFrom (from=<optimized out>, this=<optimized out>) at core/state.h:366
#1  0x00005555555bdedd in (anonymous namespace)::Heap::markFrom (this=0x7fffffffd1c0, v=...) at core/state.h:345
#2  (anonymous namespace)::Interpreter::makeHeap<(anonymous namespace)::HeapThunk, Identifier const*&, std::nullptr_t, int, std::nullptr_t>(decltype(nullptr) &&, int &&, decltype(nullptr) &&, const Identifier *&) (this=this@entry=0x7fffffffd1c0) at core/vm.cpp:542
#3  0x00005555555d5a8f in (anonymous namespace)::Interpreter::otherJsonToHeap (this=this@entry=0x7fffffffd1c0, v=..., filled=@0x555555f102aa: true, attach=...) at core/vm.cpp:1560
#4  0x00005555555d595c in (anonymous namespace)::Interpreter::otherJsonToHeap (this=this@entry=0x7fffffffd1c0, v=..., filled=@0x555555f1014a: true, attach=...) at core/vm.cpp:1573
#5  0x00005555555d595c in (anonymous namespace)::Interpreter::otherJsonToHeap (this=this@entry=0x7fffffffd1c0, v=..., filled=@0x555555f0ff4a: true, attach=...) at core/vm.cpp:1573
#6  0x00005555555d595c in (anonymous namespace)::Interpreter::otherJsonToHeap (this=this@entry=0x7fffffffd1c0, v=..., filled=@0x7fffffffc95f: true, attach=...) at core/vm.cpp:1573
#7  0x00005555555d65a2 in (anonymous namespace)::Interpreter::builtinParseJson (this=0x7fffffffd1c0, loc=..., args=...) at core/vm.cpp:1524
#8  0x00005555555cca72 in (anonymous namespace)::Interpreter::evaluate (this=this@entry=0x7fffffffd1c0, ast_=<optimized out>, ast_@entry=0x555555828ea0, initial_stack_size=1) at core/vm.cpp:2463
#9  0x00005555555d144e in (anonymous namespace)::Interpreter::manifestJson (this=this@entry=0x7fffffffd1c0, loc=..., indent=..., multiline=true) at core/vm.cpp:3016
#10 0x00005555555d396e in jsonnet_vm_execute (alloc=alloc@entry=0x7fffffffd710, ast=<optimized out>, ext_vars=..., max_stack=max_stack@entry=502, gc_min_objects=<optimized out>,
    gc_growth_trigger=<optimized out>, natives=..., import_callback=0x555555598c20 <default_import_callback(void*, char const*, char const*, char**, int*)>, ctx=0x555555824a80, string_output=false)
    at core/vm.cpp:3135
#11 0x0000555555594aa0 in jsonnet_evaluate_snippet_aux (vm=0x555555824a80, filename=<optimized out>, snippet=<optimized out>, error=0x7fffffffd990, kind=(anonymous namespace)::REGULAR)
    at core/libjsonnet.cpp:516
---Type <return> to continue, or q <return> to quit---
#12 0x0000555555594e8b in jsonnet_evaluate_snippet (vm=<optimized out>, filename=<optimized out>, snippet=<optimized out>, error=<optimized out>) at core/libjsonnet.cpp:667
#13 0x000055555555ebbd in main (argc=<optimized out>, argv=<optimized out>) at cmd/jsonnet.cpp:786
(gdb)
```

reproduction case files in here

https://gist.github.com/slene/b81c8eb2d70eb4ea49b64a8b291cb208

**Comment by sbarzowski** [comment]
Oops. Thanks for reporting. 

I was able to reproduce and reduce the example a little:
```
std.type(std.parseJson(std.extVar('config')))
```
Funnily enough this doesn't crash:
```
std.parseJson(std.extVar('config'))
```

I also have a potential fix, but I want to make sure it's getting to the bottom of the issue. The problem seems to be that when converting parsed JSON array to a runtime value, the runtime array starts with nullptrs as elements and they are filled one by one. So if GC triggers during that time it can reach some nulls. Pushing only actual HeapThunks instead of initializing with nulls fixes the crash for me (valgrind passes cleanly). 

Random idea for later: perhaps we cab run garbage collector more aggressively during tests?

**Comment by slene** [comment]
@sbarzowski Thanks! The bug fix resolved.
