### ISSUE TITLE
Python3: TLA  vars doesn't work

### ISSUE THREAD

**Issue by redbaron** [google/jsonnet#720]
It seems that at least for python3 tla vars don't work:

```
Python 3.6.9 (default, Sep 12 2019, 16:42:31) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import _jsonnet

>>> _jsonnet.evaluate_snippet('', 'x', tla_codes={'x': '{}'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: STATIC ERROR: 1:1: Unknown variable: x

>>> _jsonnet.evaluate_snippet('', 'x', tla_vars={'x': '99'})                                                                                                                                   
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: STATIC ERROR: 1:1: Unknown variable: x
```

**Comment by sbarzowski** [comment]
Well, that is not how TLAs are used. TLAs are top-level-arguments to a top level function. So you would need to do something like that instead:

```
>>> _jsonnet.evaluate_snippet('', 'function(x) x + 17', tla_codes={'x': '17'})
'34\n'
```

I hope that helps.

**Comment by redbaron** [comment]
@sbarzowski,  oh, I didn't realise there is an implicit top level function, thanks!
