### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by alamie** [google/jsonnet#910]
I'm using Python 3.8.3 and `jsonnet==0.17.0`.
My `config.jsonnet` file looks like this:
```
local n_jobs_pipeline = 1;
{
  "model":{
    "n_jobs": n_jobs_pipeline
  }
}
```
I'm reading this naive config file as follows:
```python
from pathlib import Path
import json

fpath = Path('config.jsonnet')
with open(fpath, 'r') as f:
    params = json.load(f)
```
which gives me the following error:
```
Traceback (most recent call last):
  File "/project/config/toto.py", line 7, in <module>
    params = json.load(f)
  File "/opt/anaconda3/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/opt/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
What am I doing wrong? Is it because `jsonnet==0.17.0` is not compatible with Python 3.8?

**Comment by alamie** [comment]
My bad, reading jsonnet files works fine with:
```
def read_jsonnet_file(f):
    return json.loads(_jsonnet.evaluate_file(f))
```
